### ISSUE TITLE
Kubernetes Deployment?

### ISSUE THREAD

**Issue by QuinnBast** [geodocker/geodocker#6]
Is this repository/project still alive? If no, is there anywhere I could find a more active project?

You have a docker-compose deployment, but these services are supposed to be deployed clustered. Is there anywhere i can find a Helm chart or Kubernetes deployment for these?

**Comment by pomadchin** [comment]
Hey @QuinnBast it is not alive / not actively maintained, feel free to contribute though if there is any interest!
